// ignore_for_file: non_constant_identifier_names

Map<String, String> names_de = {
  "USD": "US-Dollar",
  "EUR": "Euro",
  "JPY": "Japanischer Yen",
  "GBP": "Britisches Pfund",
  "AUD": "Australischer Dollar",
  "CAD": "Kanadischer Dollar",
  "CHF": "Schweizer Franken",
  "CNY": "Chinesischer Yuan Renminbi",
  "HKD": "Hongkong-Dollar",
  "NZD": "Neuseeland-Dollar",
  "SEK": "Schwedische Krone",
  "KRW": "Südkoreanischer Won",
  "SGD": "Singapur-Dollar",
  "NOK": "Norwegische Krone",
  "MXN": "Mexikanischer Peso",
  "INR": "Indische Rupie",
  "RUB": "Russischer Rubel",
  "ZAR": "Südafrikanischer Rand",
  "TRY": "Türkische Lira",
  "BRL": "Brasilianischer Real",
  "TWD": "Taiwanesischer Dollar",
  "DKK": "Dänische Krone",
  "PLN": "Polnischer Zloty",
  "THB": "Thailändischer Baht",
  "IDR": "Indonesische Rupiah",
  "HUF": "Ungarischer Forint",
  "CZK": "Tschechische Krone",
  "ILS": "Israelischer Schekel",
  "CLP": "Chilenischer Peso",
  "PHP": "Philippinischer Peso",
  "AED": "VAE-Dirham",
  "COP": "Kolumbianischer Peso",
  "SAR": "Saudi-Rial",
  "MYR": "Malaysischer Ringgit",
  "RON": "Rumänischer Leu",
  "AFN": "Afghani",
  "ALL": "Albanischer Lek",
  "DZD": "Algerischer Dinar",
  "AOA": "Angolanischer Kwanza",
  "ARS": "Argentinischer Peso",
  "AMD": "Armenischer Dram",
  "AZN": "Aserbaidschan-Manat",
  "BHD": "Bahrain-Dinar",
  "BDT": "Bangladesch-Taka",
  "BBD": "Barbados-Dollar",
  "BYN": "Weißrussischer Rubel",
  "BZD": "Belize-Dollar",
  "BMD": "Bermuda-Dollar",
  "BTN": "Bhutan-Ngultrum",
  "BOB": "Bolivianischer Bolíviano",
  "BAM": "Bosnisch-Herzegowinische Mark",
  "BWP": "Botswanischer Pula",
  "BND": "Brunei-Dollar",
  "BGN": "Bulgarischer Lew",
  "BIF": "Burundischer Franc",
  "KHR": "Kambodschanischer Riel",
  "KYD": "Kaiman-Dollar",
  "XAF": "Zentralafrikanischer CFA-Franc",
  "XOF": "Westafrikanischer CFA-Franc",
  "CDF": "Kongolesischer Franc",
  "CRC": "Costa-Rica-Colón",
  "CUP": "Kubanischer Peso",
  "DOP": "Dominikanischer Peso",
  "EGP": "Ägyptisches Pfund",
  "ETB": "Äthiopischer Birr",
  "GMD": "Gambischer Dalasi",
  "GEL": "Georgischer Lari",
  "GHS": "Ghanaischer Cedi",
  "GTQ": "Guatemaltekischer Quetzal",
  "GYD": "Guyana-Dollar",
  "HTG": "Haitianische Gourde",
  "ISK": "Isländische Krone",
  "IQD": "Irakischer Dinar",
  "JMD": "Jamaika-Dollar",
  "JOD": "Jordanischer Dinar",
  "KZT": "Kasachischer Tenge",
  "KES": "Kenianischer Schilling",
  "KWD": "Kuwait-Dinar",
  "KGS": "Kirgisischer Som",
  "LAK": "Laotischer Kip",
  "LBP": "Libanesisches Pfund",
  "LRD": "Liberianischer Dollar",
  "MKD": "Mazedonischer Denar",
  "MGA": "Madagassischer Ariary",
  "MWK": "Malawischer Kwacha",
  "MVR": "Maledivische Rufiyaa",
  "MUR": "Mauritius-Rupie",
  "MDL": "Moldawischer Leu",
  "MNT": "Mongolischer Tugrik",
  "MAD": "Marokkanischer Dirham",
  "MZN": "Mosambikanischer Metical",
  "MMK": "Myanmarischer Kyat",
  "NAD": "Namibia-Dollar",
  "NPR": "Nepalesische Rupie",
  "NIO": "Nicaraguanischer Córdoba",
  "NGN": "Nigerianischer Naira",
  "OMR": "Omanischer Rial",
  "PKR": "Pakistanische Rupie",
  "PGK": "Papua-Neuguinea-Kina",
  "PYG": "Paraguay-Guaraní",
  "PEN": "Peruanischer Sol",
  "QAR": "Katar-Riyal",
  "RWF": "Ruandischer Franc",
  "RSD": "Serbischer Dinar",
  "SCR": "Seychellen-Rupie",
  "SOS": "Somalischer Schilling",
  "LKR": "Sri-Lanka-Rupie",
  "SRD": "Suriname-Dollar",
  "SYP": "Syrisches Pfund",
  "TZS": "Tansanischer Schilling",
  "TOP": "Tongaische Pa'anga",
  "TTD": "Trinidad-und-Tobago-Dollar",
  "TND": "Tunesischer Dinar",
  "UGX": "Ugandischer Schilling",
  "UAH": "Ukrainische Hrywnja",
  "UYU": "Uruguayischer Peso",
  "VES": "Venezolanischer Bolívar",
  "VND": "Vietnamesischer Dong",
  "YER": "Jemenitischer Rial",
  "ZMW": "Sambischer Kwacha",
  "ZWL": "Simbabwischer Dollar",
};

Map<String, String> pluralNames_de = {
  "USD": "US-Dollars",
  "EUR": "Euros",
  "JPY": "Japanische Yen",
  "GBP": "Britische Pfund Sterling",
  "AUD": "Australische Dollars",
  "CAD": "Kanadische Dollars",
  "CHF": "Schweizer Franken",
  "CNY": "Chinesische Yuan",
  "HKD": "Hongkong-Dollars",
  "NZD": "Neuseeland-Dollars",
  "SEK": "Schwedische Kronen",
  "KRW": "Südkoreanische Won",
  "SGD": "Singapur-Dollars",
  "NOK": "Norwegische Kronen",
  "MXN": "Mexikanische Pesos",
  "INR": "Indische Rupien",
  "RUB": "Russische Rubel",
  "ZAR": "Südafrikanische Rand",
  "TRY": "Türkische Lira",
  "BRL": "Brasilianische Reais",
  "TWD": "Neuer Taiwan-Dollar",
  "DKK": "Dänische Kronen",
  "PLN": "Polnische Zloty",
  "THB": "Thailändische Baht",
  "IDR": "Indonesische Rupiah",
  "HUF": "Ungarische Forint",
  "CZK": "Tschechische Kronen",
  "ILS": "Israelische Neue Schekel",
  "CLP": "Chilenische Pesos",
  "PHP": "Philippinische Pesos",
  "AED": "VAE-Dirhams",
  "COP": "Kolumbianische Pesos",
  "SAR": "Saudi-Rial",
  "MYR": "Malaysische Ringgits",
  "RON": "Rumänische Lei",
  "AFN": "Afghanische Afghanis",
  "ALL": "Albanische Lekë",
  "DZD": "Algerische Dinar",
  "AOA": "Angolanische Kwanzas",
  "ARS": "Argentinische Pesos",
  "AMD": "Armenische Dram",
  "AZN": "Aserbaidschanische Manats",
  "BHD": "Bahrain-Dinar",
  "BDT": "Bangladeschische Taka",
  "BBD": "Barbados-Dollars",
  "BYN": "Weißrussische Rubel",
  "BZD": "Belize-Dollars",
  "BMD": "Bermuda-Dollars",
  "BTN": "Bhutanische Ngultrum",
  "BOB": "Bolivianische Bolivianos",
  "BAM": "Bosnische Konvertierbare Mark",
  "BWP": "Botswanische Pula",
  "BND": "Brunei-Dollars",
  "BGN": "Bulgarische Leva",
  "BIF": "Burundische Francs",
  "KHR": "Kambodschanische Riel",
  "KYD": "Kaiman-Dollar",
  "XAF": "Zentralafrikanische CFA-Francs",
  "XOF": "Westafrikanische CFA-Francs",
  "CDF": "Kongolesische Francs",
  "CRC": "Costa-Rica-Colóns",
  "CUP": "Kubanische Pesos",
  "DOP": "Dominikanische Pesos",
  "EGP": "Ägyptische Pfund",
  "ETB": "Äthiopische Birr",
  "GMD": "Gambische Dalasis",
  "GEL": "Georgische Lari",
  "GHS": "Ghanaische Cedis",
  "GTQ": "Guatemaltekische Quetzales",
  "GYD": "Guyana-Dollars",
  "HTG": "Haitianische Gourdes",
  "ISK": "Isländische Krónur",
  "IQD": "Irakische Dinar",
  "JMD": "Jamaikanische Dollars",
  "JOD": "Jordanische Dinar",
  "KZT": "Kasachische Tenges",
  "KES": "Kenianische Schilling",
  "KWD": "Kuwaitische Dinar",
  "KGS": "Kirgisische Som",
  "LAK": "Laotische Kip",
  "LBP": "Libanesische Pfund",
  "LRD": "Liberianische Dollars",
  "MKD": "Mazedonische Denari",
  "MGA": "Madagassische Ariary",
  "MWK": "Malawische Kwachas",
  "MVR": "Maledivische Rufiyaa",
  "MUR": "Mauritische Rupien",
  "MDL": "Moldauische Lei",
  "MNT": "Mongolische Tugrik",
  "MAD": "Marokkanische Dirhams",
  "MZN": "Mosambikanische Meticals",
  "MMK": "Myanmarische Kyats",
  "NAD": "Namibische Dollars",
  "NPR": "Nepalesische Rupien",
  "NIO": "Nicaraguanische Córdobas",
  "NGN": "Nigerianische Nairas",
  "OMR": "Omanische Rials",
  "PKR": "Pakistanische Rupien",
  "PGK": "Papua-Neuguinea-Kina",
  "PYG": "Paraguayische Guaranis",
  "PEN": "Peruanische Nuevos Soles",
  "QAR": "Katar-Rials",
  "RWF": "Ruandische Francs",
  "RSD": "Serbische Dinar",
  "SCR": "Seychellen-Rupien",
  "SOS": "Somalische Schilling",
  "LKR": "Sri-Lanka-Rupien",
  "SRD": "Suriname-Dollars",
  "SYP": "Syrische Lira",
  "TZS": "Tansanische Schilling",
  "TOP": "Tongaische Pa'angas",
  "TTD": "Trinidad-und-Tobago-Dollars",
  "TND": "Tunesische Dinar",
  "UGX": "Ugandische Schilling",
  "UAH": "Ukrainische Hrywnja",
  "UYU": "Uruguayische Pesos",
  "VES": "Venezolanische Bolívars",
  "VND": "Vietnamesische Dong",
  "YER": "Jemen-Rials",
  "ZMW": "Sambische Kwachas",
  "ZWL": "Simbabwische Dollars",
};
