// ignore_for_file: non_constant_identifier_names

Map<String, String> names_en = {
  "USD": "United States Dollar",
  "EUR": "Euro",
  "JPY": "Japanese Yen",
  "GBP": "British Pound",
  "AUD": "Australian Dollar",
  "CAD": "Canadian Dollar",
  "CHF": "Switzerland Franc",
  "CNY": "China Yuan Renminbi",
  "HKD": "Hong Kong Dollar",
  "NZD": "New Zealand Dollar",
  "SEK": "Sweden Krona",
  "KRW": "South Korea Won",
  "SGD": "Singapore Dollar",
  "NOK": "Norway Krone",
  "MXN": "Mexico Peso",
  "INR": "Indian Rupee",
  "RUB": "Russia Ruble",
  "ZAR": "South Africa Rand",
  "TRY": "Turkish Lira",
  "BRL": "Brazilian Real",
  "TWD": "Taiwan New Dollar",
  "DKK": "Denmark Krone",
  "PLN": "Poland Zloty",
  "THB": "Thailand Baht",
  "IDR": "Indonesia Rupiah",
  "HUF": "Hungary Forint",
  "CZK": "Czech Koruna",
  "ILS": "Israel Shekel",
  "CLP": "Chile Peso",
  "PHP": "Philippines Peso",
  "AED": "Emirati Dirham",
  "COP": "Colombia Peso",
  "SAR": "Saudi Arabia Riyal",
  "MYR": "Malaysia Ringgit",
  "RON": "Romania Leu",
  "AFN": "Afghanistan Afghani",
  "ALL": "Albanian Lek",
  "DZD": "Algerian dinar",
  "AOA": "Angolan Kwanza",
  "ARS": "Argentine Peso",
  "AMD": "Armenian Dram",
  "AZN": "Azerbaijani Manat",
  "BHD": "Bahraini Dinar",
  "BDT": "Bangladeshi Taka",
  "BBD": "Barbados Dollar",
  "BYN": "Belarussian Ruble",
  "BZD": "Belize Dollar",
  "BMD": "Bermuda Dollar",
  "BTN": "Bhutanese Ngultrum",
  "BOB": "Bolivia Bolíviano",
  "BAM": "Bosnia and Herzegovina convertible mark",
  "BWP": "Botswanan Pula",
  "BND": "Brunei Darussalam Dollar",
  "BGN": "Bulgarian Lev",
  "BIF": "Burundian Franc",
  "KHR": "Cambodian riel",
  "KYD": "Cayman Islands Dollar",
  "XAF": "Central African CFA franc",
  "XOF": "UEMOA CFA franc",
  "CDF": "Congolese franc",
  "CRC": "Costa Rica Colon",
  "CUP": "Cuban Peso",
  "DOP": "Dominican Republic Peso",
  "EGP": "Egypt Pound",
  "ETB": "Ethiopian Birr",
  "GMD": "Gambian dalasi",
  "GEL": "Georgian Lari",
  "GHS": "Ghana Cedi",
  "GTQ": "Guatemalan quetzal",
  "GYD": "Guyana Dollar",
  "HTG": "Haitian gourde",
  "ISK": "Iceland Krona",
  "IQD": "Iraqi Dinar",
  "JMD": "Jamaica Dollar",
  "JOD": "Jordanian dinar",
  "KZT": "Kazakhstan Tenge",
  "KES": "Kenyan Shilling",
  "KWD": "Kuwaiti Dinar",
  "KGS": "Kyrgyzstani som",
  "LAK": "Laos Kip",
  "LBP": "Lebanese Pound",
  "LRD": "Liberia Dollar",
  "MKD": "Macedonia Denar",
  "MGA": "Malagasy Ariary",
  "MWK": "Malawian Kwacha",
  "MVR": "Maldivian Rufiyaa",
  "MUR": "Mauritius Rupee",
  "MDL": "Moldovan Leu",
  "MNT": "Mongolia Tughrik",
  "MAD": "Moroccan Dirham",
  "MZN": "Mozambique Metical",
  "MMK": "Myanmar Kyat",
  "NAD": "Namibia Dollar",
  "NPR": "Nepal Rupee",
  "NIO": "Nicaragua Cordoba",
  "NGN": "Nigeria Naira",
  "OMR": "Oman Rial",
  "PKR": "Pakistan Rupee",
  "PGK": "Papua New Guinean Kina",
  "PYG": "Paraguay Guarani",
  "PEN": "Peru Sol",
  "QAR": "Qatar Riyal",
  "RWF": "Rwandan franc",
  "RSD": "Serbia Dinar",
  "SCR": "Seychellois rupee",
  "SOS": "Somalia Shilling",
  "LKR": "Sri Lanka Rupee",
  "SRD": "Suriname Dollar",
  "SYP": "Syrian Lira",
  "TZS": "Tanzanian Shilling",
  "TOP": "Tongan Pa'anga",
  "TTD": "Trinidad and Tobago Dollar",
  "TND": "Tunisian dinar",
  "UGX": "Ugandan Shilling",
  "UAH": "Ukraine Hryvnia",
  "UYU": "Uruguay Peso",
  "VEF": "Venezuela Bolívar",
  "VND": "Vietnamese Dong",
  "YER": "Yemen Rial",
  "ZMW": "Zambian kwacha",
  "ZWL": "Zimbabwean Dollar",
};

Map<String, String> pluralNames_en = {
  "USD": "US dollars",
  "EUR": "Euros",
  "JPY": "Japanese yen",
  "GBP": "British pounds sterling",
  "AUD": "Australian dollars",
  "CAD": "Canadian dollars",
  "CHF": "Swiss francs",
  "CNY": "Chinese yuan",
  "HKD": "Hong Kong dollars",
  "NZD": "New Zealand dollars",
  "SEK": "Swedish kronor",
  "KRW": "South Korean won",
  "SGD": "Singapore dollars",
  "NOK": "Norwegian kroner",
  "MXN": "Mexican pesos",
  "INR": "Indian rupees",
  "RUB": "Russian rubles",
  "ZAR": "South African rand",
  "TRY": "Turkish Lira",
  "BRL": "Brazilian Reais",
  "TWD": "New Taiwan dollars",
  "DKK": "Danish kroner",
  "PLN": "Polish zlotys",
  "THB": "Thai baht",
  "IDR": "Indonesian rupiahs",
  "HUF": "Hungarian forints",
  "CZK": "Czech Republic korunas",
  "ILS": "Israeli new sheqels",
  "CLP": "Chilean pesos",
  "PHP": "Philippine pesos",
  "AED": "UAE dirhams",
  "COP": "Colombian pesos",
  "SAR": "Saudi riyals",
  "MYR": "Malaysian ringgits",
  "RON": "Romanian lei",
  "AFN": "Afghan Afghanis",
  "ALL": "Albanian lekë",
  "DZD": "Algerian dinars",
  "AOA": "Angolan kwanzas",
  "ARS": "Argentine pesos",
  "AMD": "Armenian drams",
  "AZN": "Azerbaijani manats",
  "BHD": "Bahraini dinars",
  "BDT": "Bangladeshi takas",
  "BBD": "Barbados dollars",
  "BYN": "Belarusian rubles",
  "BZD": "Belize dollars",
  "BMD": "Bermuda dollars",
  "BTN": "Bhutanese ngultrums",
  "BOB": "Bolivian bolivianos",
  "BAM": "Bosnia and Herzegovina convertible marks",
  "BWP": "Botswanan pulas",
  "BND": "Brunei dollars",
  "BGN": "Bulgarian leva",
  "BIF": "Burundian Franc",
  "KHR": "Cambodian riels",
  "KYD": "Cayman islands dollars",
  "XAF": "Central African CFA francs",
  "XOF": "UEMOA CFA francs",
  "CDF": "Congolese francs",
  "CRC": "Costa Rican colóns",
  "CUP": "Cuban pesos",
  "DOP": "Dominican pesos",
  "EGP": "Egyptian pounds",
  "ETB": "Ethiopian birrs",
  "GMD": "Gambian dalasis",
  "GEL": "Georgian laris",
  "GHS": "Ghanaian cedis",
  "GTQ": "Guatemalan quetzales",
  "GYD": "Guyana dollars",
  "HTG": "Haitian gourdes",
  "ISK": "Icelandic krónur",
  "IQD": "Iraqi dinars",
  "JMD": "Jamaican dollars",
  "JOD": "Jordanian dinars",
  "KZT": "Kazakhstani tenges",
  "KES": "Kenyan shillings",
  "KWD": "Kuwaiti dinars",
  "KGS": "Kyrgyzstani som",
  "LAK": "Laos Kip",
  "LBP": "Lebanese pounds",
  "LRD": "Liberia dollars",
  "MKD": "Macedonian denari",
  "MGA": "Malagasy ariaries",
  "MWK": "Malawian kwachas",
  "MVR": "Maldivian Rufiyaa",
  "MUR": "Mauritian rupees",
  "MDL": "Moldovan lei",
  "MNT": "Mongolia tugriks",
  "MAD": "Moroccan dirhams",
  "MZN": "Mozambican meticals",
  "MMK": "Myanmar Kyats",
  "NAD": "Namibian dollars",
  "NPR": "Nepalese rupees",
  "NIO": "Nicaraguan córdobas",
  "NGN": "Nigerian nairas",
  "OMR": "Omani rials",
  "PKR": "Pakistani rupees",
  "PGK": "Papua New Guinean Kina",
  "PYG": "Paraguayan guaranis",
  "PEN": "Peruvian nuevos soles",
  "QAR": "Qatari rials",
  "RWF": "Rwandan francs",
  "RSD": "Serbian dinars",
  "SCR": "Seychelles rupee",
  "SOS": "Somali shillings",
  "LKR": "Sri Lankan rupees",
  "SRD": "Suriname Dollars",
  "SYP": "Syrian lira",
  "TZS": "Tanzanian shillings",
  "TOP": "Tongan pa'angas",
  "TTD": "Trinidad and Tobago dollars",
  "TND": "Tunisian dinars",
  "UGX": "Ugandan shillings",
  "UAH": "Ukrainian hryvnias",
  "UYU": "Uruguayan pesos",
  "VEF": "Venezuelan bolívars",
  "VND": "Vietnamese dong",
  "YER": "Yemeni rials",
  "ZMW": "Zambian kwachas",
  "ZWL": "Zimbabwean dollars",
};
