// ignore_for_file: non_constant_identifier_names

Map<String, String> names_es = {
  "USD": "Dólar estadounidense",
  "EUR": "Euro",
  "JPY": "Yen japonés",
  "GBP": "Libra esterlina",
  "AUD": "Dólar australiano",
  "CAD": "Dólar canadiense",
  "CHF": "Franco suizo",
  "CNY": "Yuan renminbi chino",
  "HKD": "Dólar de Hong Kong",
  "NZD": "Dólar neozelandés",
  "SEK": "Corona sueca",
  "KRW": "Won surcoreano",
  "SGD": "Dólar de Singapur",
  "NOK": "Corona noruega",
  "MXN": "Peso mexicano",
  "INR": "Rupia india",
  "RUB": "Rublo ruso",
  "ZAR": "Rand sudafricano",
  "TRY": "Lira turca",
  "BRL": "Real brasileño",
  "TWD": "Nuevo dólar taiwanés",
  "DKK": "Corona danesa",
  "PLN": "Zloty polaco",
  "THB": "Baht tailandés",
  "IDR": "Rupia indonesia",
  "HUF": "Forinto húngaro",
  "CZK": "Corona checa",
  "ILS": "Shekel israelí",
  "CLP": "Peso chileno",
  "PHP": "Peso filipino",
  "AED": "Dírham emiratí",
  "COP": "Peso colombiano",
  "SAR": "Riyal saudí",
  "MYR": "Ringgit malasio",
  "RON": "Leu rumano",
  "AFN": "Afgani afgano",
  "ALL": "Lek albanés",
  "DZD": "Dinar argelino",
  "AOA": "Kwanza angoleño",
  "ARS": "Peso argentino",
  "AMD": "Dram armenio",
  "AZN": "Manat azerbaiyano",
  "BHD": "Dinar bareiní",
  "BDT": "Taka de Bangladés",
  "BBD": "Dólar de Barbados",
  "BYN": "Rublo bielorruso",
  "BZD": "Dólar beliceño",
  "BMD": "Dólar bermudeño",
  "BTN": "Ngultrum butanés",
  "BOB": "Boliviano",
  "BAM": "Marco convertible de Bosnia y Herzegovina",
  "BWP": "Pula de Botsuana",
  "BND": "Dólar de Brunéi",
  "BGN": "Lev búlgaro",
  "BIF": "Franco burundés",
  "KHR": "Riel camboyano",
  "KYD": "Dólar de las Islas Caimán",
  "XAF": "Franco CFA de África Central",
  "XOF": "Franco CFA de África Occidental",
  "CDF": "Franco congoleño",
  "CRC": "Colón costarricense",
  "CUP": "Peso cubano",
  "DOP": "Peso dominicano",
  "EGP": "Libra egipcia",
  "ETB": "Birr etíope",
  "GMD": "Dalasi gambiano",
  "GEL": "Lari georgiano",
  "GHS": "Cedi ghanés",
  "GTQ": "Quetzal guatemalteco",
  "GYD": "Dólar guyanés",
  "HTG": "Gourde haitiano",
  "ISK": "Corona islandesa",
  "IQD": "Dinar iraquí",
  "JMD": "Dólar jamaicano",
  "JOD": "Dinar jordano",
  "KZT": "Tenge kazajo",
  "KES": "Chelín keniano",
  "KWD": "Dinar kuwaití",
  "KGS": "Som kirguís",
  "LAK": "Kip laosiano",
  "LBP": "Libra libanesa",
  "LRD": "Dólar liberiano",
  "MKD": "Denar macedonio",
  "MGA": "Ariary malgache",
  "MWK": "Kwacha malauí",
  "MVR": "Rufiyaa maldiva",
  "MUR": "Rupia mauriciana",
  "MDL": "Leu moldavo",
  "MNT": "Tugrik mongol",
  "MAD": "Dírham marroquí",
  "MZN": "Metical mozambiqueño",
  "MMK": "Kyat birmano",
  "NAD": "Dólar namibio",
  "NPR": "Rupia nepalesa",
  "NIO": "Córdoba nicaragüense",
  "NGN": "Naira nigeriana",
  "OMR": "Rial omaní",
  "PKR": "Rupia pakistaní",
  "PGK": "Kina de Papúa Nueva Guinea",
  "PYG": "Guaraní paraguayo",
  "PEN": "Sol peruano",
  "QAR": "Riyal catarí",
  "RWF": "Franco ruandés",
  "RSD": "Dinar serbio",
  "SCR": "Rupia de Seychelles",
  "SOS": "Chelín somalí",
  "LKR": "Rupia de Sri Lanka",
  "SRD": "Dólar surinamés",
  "SYP": "Libra siria",
  "TZS": "Chelín tanzano",
  "TOP": "Paʻanga tongano",
  "TTD": "Dólar de Trinidad y Tobago",
  "TND": "Dinar tunecino",
  "UGX": "Chelín ugandés",
  "UAH": "Grivna ucraniana",
  "UYU": "Peso uruguayo",
  "VES": "Bolívar venezolano",
  "VND": "Dong vietnamita",
  "YER": "Rial yemení",
  "ZMW": "Kwacha zambiano",
  "ZWL": "Dólar zimbabuense",
};

Map<String, String> pluralNames_es = {
  "USD": "dólares estadounidenses",
  "EUR": "euros",
  "JPY": "yenes japoneses",
  "GBP": "libras esterlinas británicas",
  "AUD": "dólares australianos",
  "CAD": "dólares canadienses",
  "CHF": "francos suizos",
  "CNY": "yuanes chinos",
  "HKD": "dólares de Hong Kong",
  "NZD": "dólares neozelandeses",
  "SEK": "coronas suecas",
  "KRW": "wones surcoreanos",
  "SGD": "dólares de Singapur",
  "NOK": "coronas noruegas",
  "MXN": "pesos mexicanos",
  "INR": "rupias indias",
  "RUB": "rublos rusos",
  "ZAR": "rands sudafricanos",
  "TRY": "liras turcas",
  "BRL": "reales brasileños",
  "TWD": "nuevos dólares taiwaneses",
  "DKK": "coronas danesas",
  "PLN": "zlotys polacos",
  "THB": "baht tailandeses",
  "IDR": "rupias indonesias",
  "HUF": "forintos húngaros",
  "CZK": "coronas checas",
  "ILS": "nuevos shéqueles israelíes",
  "CLP": "pesos chilenos",
  "PHP": "pesos filipinos",
  "AED": "dírhams de los Emiratos Árabes Unidos",
  "COP": "pesos colombianos",
  "SAR": "riales saudíes",
  "MYR": "ringgits malayos",
  "RON": "lei rumanos",
  "AFN": "afganis afganos",
  "ALL": "lekë albaneses",
  "DZD": "dinares argelinos",
  "AOA": "kwanzas angoleños",
  "ARS": "pesos argentinos",
  "AMD": "drams armenios",
  "AZN": "manats azerbaiyanos",
  "BHD": "dinares bahreiníes",
  "BDT": "takas bangladesíes",
  "BBD": "dólares de Barbados",
  "BYN": "rublos bielorrusos",
  "BZD": "dólares beliceños",
  "BMD": "dólares de Bermudas",
  "BTN": "ngultrums butaneses",
  "BOB": "bolivianos bolivianos",
  "BAM": "marcos convertibles de Bosnia y Herzegovina",
  "BWP": "pulas botswaneses",
  "BND": "dólares de Brunéi",
  "BGN": "levas búlgaras",
  "BIF": "francos burundeses",
  "KHR": "rieles camboyanos",
  "KYD": "dólares de las Islas Caimán",
  "XAF": "francos CFA de África Central",
  "XOF": "francos CFA de la UEMOA",
  "CDF": "francos congoleños",
  "CRC": "colones costarricenses",
  "CUP": "pesos cubanos",
  "DOP": "pesos dominicanos",
  "EGP": "libras egipcias",
  "ETB": "birrs etíopes",
  "GMD": "dalasis gambianos",
  "GEL": "laris georgianos",
  "GHS": "cedis ghaneses",
  "GTQ": "quetzales guatemaltecos",
  "GYD": "dólares guyaneses",
  "HTG": "gourdes haitianos",
  "ISK": "coronas islandesas",
  "IQD": "dinares iraquíes",
  "JMD": "dólares jamaiquinos",
  "JOD": "dinares jordanos",
  "KZT": "tenges kazajos",
  "KES": "chelines kenianos",
  "KWD": "dinares kuwaitíes",
  "KGS": "soms kirguises",
  "LAK": "kips laosianos",
  "LBP": "libras libanesas",
  "LRD": "dólares liberianos",
  "MKD": "denares macedonios",
  "MGA": "ariarys malgaches",
  "MWK": "kwachas malauíes",
  "MVR": "rufiyaas maldivas",
  "MUR": "rupias mauricianas",
  "MDL": "lei moldavos",
  "MNT": "tugriks mongoles",
  "MAD": "dírhams marroquíes",
  "MZN": "meticales mozambiqueños",
  "MMK": "kyats birmanos",
  "NAD": "dólares namibios",
  "NPR": "rupias nepalesas",
  "NIO": "córdobas nicaragüenses",
  "NGN": "nairas nigerianos",
  "OMR": "riales omaníes",
  "PKR": "rupias pakistaníes",
  "PGK": "kinas papúes",
  "PYG": "guaraníes paraguayos",
  "PEN": "nuevos soles peruanos",
  "QAR": "riales cataríes",
  "RWF": "francos ruandeses",
  "RSD": "dinares serbios",
  "SCR": "rupias seychellenses",
  "SOS": "chelines somalíes",
  "LKR": "rupias de Sri Lanka",
  "SRD": "dólares surinameses",
  "SYP": "liras sirias",
  "TZS": "chelines tanzanos",
  "TOP": "pa'angas tonganos",
  "TTD": "dólares de Trinidad y Tobago",
  "TND": "dinares tunecinos",
  "UGX": "chelines ugandeses",
  "UAH": "grivnias ucranianas",
  "UYU": "pesos uruguayos",
  "VES": "bolívares venezolanos",
  "VND": "dongs vietnamitas",
  "YER": "riales yemeníes",
  "ZMW": "kwachas zambianos",
  "ZWL": "dólares zimbabuenses",
};
