// ignore_for_file: non_constant_identifier_names

Map<String, String> names_fr = {
  "USD": "Dollar américain",
  "EUR": "Euro",
  "JPY": "Yen japonais",
  "GBP": "Livre sterling",
  "AUD": "Dollar australien",
  "CAD": "Dollar canadien",
  "CHF": "Franc suisse",
  "CNY": "Yuan renminbi chinois",
  "HKD": "Dollar de Hong Kong",
  "NZD": "Dollar néo-zélandais",
  "SEK": "Couronne suédoise",
  "KRW": "Won sud-coréen",
  "SGD": "Dollar de Singapour",
  "NOK": "Couronne norvégienne",
  "MXN": "Peso mexicain",
  "INR": "Roupie indienne",
  "RUB": "Rouble russe",
  "ZAR": "Rand sud-africain",
  "TRY": "Livre turque",
  "BRL": "Réal brésilien",
  "TWD": "Nouveau dollar taïwanais",
  "DKK": "Couronne danoise",
  "PLN": "Zloty polonais",
  "THB": "Baht thaïlandais",
  "IDR": "Roupie indonésienne",
  "HUF": "Forint hongrois",
  "CZK": "Couronne tchèque",
  "ILS": "Shekel israélien",
  "CLP": "Peso chilien",
  "PHP": "Peso philippin",
  "AED": "Dirham des Émirats arabes unis",
  "COP": "Peso colombien",
  "SAR": "Riyal saoudien",
  "MYR": "Ringgit malaisien",
  "RON": "Leu roumain",
  "AFN": "Afghani afghan",
  "ALL": "Lek albanais",
  "DZD": "Dinar algérien",
  "AOA": "Kwanza angolais",
  "ARS": "Peso argentin",
  "AMD": "Dram arménien",
  "AZN": "Manat azerbaïdjanais",
  "BHD": "Dinar bahreïni",
  "BDT": "Taka bangladais",
  "BBD": "Dollar barbadien",
  "BYN": "Rouble biélorusse",
  "BZD": "Dollar bélizéen",
  "BMD": "Dollar bermudien",
  "BTN": "Ngultrum bhoutanais",
  "BOB": "Boliviano bolivien",
  "BAM": "Mark convertible de Bosnie-Herzégovine",
  "BWP": "Pula botswanais",
  "BND": "Dollar de Brunei",
  "BGN": "Lev bulgare",
  "BIF": "Franc burundais",
  "KHR": "Riel cambodgien",
  "KYD": "Dollar des îles Caïmans",
  "XAF": "Franc CFA BEAC",
  "XOF": "Franc CFA BCEAO",
  "CDF": "Franc congolais",
  "CRC": "Colón costaricien",
  "CUP": "Peso cubain",
  "DOP": "Peso dominicain",
  "EGP": "Livre égyptienne",
  "ETB": "Birr éthiopien",
  "GMD": "Dalasi gambien",
  "GEL": "Lari géorgien",
  "GHS": "Cedi ghanéen",
  "GTQ": "Quetzal guatémaltèque",
  "GYD": "Dollar guyanais",
  "HTG": "Gourde haïtienne",
  "ISK": "Couronne islandaise",
  "IQD": "Dinar irakien",
  "JMD": "Dollar jamaïcain",
  "JOD": "Dinar jordanien",
  "KZT": "Tenge kazakh",
  "KES": "Shilling kényan",
  "KWD": "Dinar koweïtien",
  "KGS": "Som kirghize",
  "LAK": "Kip laotien",
  "LBP": "Livre libanaise",
  "LRD": "Dollar libérien",
  "MKD": "Denar macédonien",
  "MGA": "Ariary malgache",
  "MWK": "Kwacha malawien",
  "MVR": "Rufiyaa maldivienne",
  "MUR": "Roupie mauricienne",
  "MDL": "Leu moldave",
  "MNT": "Tugrik mongol",
  "MAD": "Dirham marocain",
  "MZN": "Metical mozambicain",
  "MMK": "Kyat birman",
  "NAD": "Dollar namibien",
  "NPR": "Roupie népalaise",
  "NIO": "Córdoba nicaraguayen",
  "NGN": "Naira nigérian",
  "OMR": "Rial omanais",
  "PKR": "Roupie pakistanaise",
  "PGK": "Kina papou-néo-guinéen",
  "PYG": "Guarani paraguayen",
  "PEN": "Sol péruvien",
  "QAR": "Riyal qatari",
  "RWF": "Franc rwandais",
  "RSD": "Dinar serbe",
  "SCR": "Roupie seychelloise",
  "SOS": "Shilling somalien",
  "LKR": "Roupie srilankaise",
  "SRD": "Dollar surinamien",
  "SYP": "Livre syrienne",
  "TZS": "Shilling tanzanien",
  "TOP": "Pa'anga tongien",
  "TTD": "Dollar trinidadien",
  "TND": "Dinar tunisien",
  "UGX": "Shilling ougandais",
  "UAH": "Hryvnia ukrainienne",
  "UYU": "Peso uruguayen",
  "VES": "Bolívar vénézuélien",
  "VND": "Dong vietnamien",
  "YER": "Rial yéménite",
  "ZMW": "Kwacha zambien",
  "ZWL": "Dollar zimbabwéen",
};

Map<String, String> pluralNames_fr = {
  "USD": "dollars américains",
  "EUR": "euros",
  "JPY": "yens japonais",
  "GBP": "livres sterling britanniques",
  "AUD": "dollars australiens",
  "CAD": "dollars canadiens",
  "CHF": "francs suisses",
  "CNY": "yuans chinois",
  "HKD": "dollars de Hong Kong",
  "NZD": "dollars néo-zélandais",
  "SEK": "couronnes suédoises",
  "KRW": "wons sud-coréens",
  "SGD": "dollars de Singapour",
  "NOK": "couronnes norvégiennes",
  "MXN": "pesos mexicains",
  "INR": "roupies indiennes",
  "RUB": "roubles russes",
  "ZAR": "rands sud-africains",
  "TRY": "livres turques",
  "BRL": "réaux brésiliens",
  "TWD": "nouveaux dollars taïwanais",
  "DKK": "couronnes danoises",
  "PLN": "zlotys polonais",
  "THB": "bahts thaïlandais",
  "IDR": "roupies indonésiennes",
  "HUF": "forints hongrois",
  "CZK": "couronnes tchèques",
  "ILS": "nouveaux shekels israéliens",
  "CLP": "pesos chiliens",
  "PHP": "pesos philippins",
  "AED": "dirhams des Émirats",
  "COP": "pesos colombiens",
  "SAR": "riyals saoudiens",
  "MYR": "ringgits malaisiens",
  "RON": "lei roumains",
  "AFN": "afghanis afghans",
  "ALL": "leks albanais",
  "DZD": "dinars algériens",
  "AOA": "kwanzas angolais",
  "ARS": "pesos argentins",
  "AMD": "drams arméniens",
  "AZN": "manats azerbaïdjanais",
  "BHD": "dinars bahreïnis",
  "BDT": "takas bangladais",
  "BBD": "dollars de la Barbade",
  "BYN": "roubles biélorusses",
  "BZD": "dollars du Belize",
  "BMD": "dollars des Bermudes",
  "BTN": "ngultrums bhoutanais",
  "BOB": "bolivianos boliviens",
  "BAM": "marks convertibles de Bosnie-Herzégovine",
  "BWP": "pulas botswanais",
  "BND": "dollars de Brunei",
  "BGN": "levs bulgares",
  "BIF": "francs burundais",
  "KHR": "riels cambodgiens",
  "KYD": "dollars des îles Caïmans",
  "XAF": "francs CFA d'Afrique centrale",
  "XOF": "francs CFA de l'UEMOA",
  "CDF": "francs congolais",
  "CRC": "colóns costaricains",
  "CUP": "pesos cubains",
  "DOP": "pesos dominicains",
  "EGP": "livres égyptiennes",
  "ETB": "birrs éthiopiens",
  "GMD": "dalasis gambien",
  "GEL": "laris géorgiens",
  "GHS": "cedis ghanéens",
  "GTQ": "quetzals guatémaltèques",
  "GYD": "dollars du Guyana",
  "HTG": "gourdes haïtiennes",
  "ISK": "couronnes islandaises",
  "IQD": "dinars irakiens",
  "JMD": "dollars jamaïcains",
  "JOD": "dinars jordaniens",
  "KZT": "tengues kazakhs",
  "KES": "shillings kenyans",
  "KWD": "dinars koweïtiens",
  "KGS": "soms kirghizes",
  "LAK": "kips laotiens",
  "LBP": "livres libanaises",
  "LRD": "dollars libériens",
  "MKD": "denars macédoniens",
  "MGA": "ariarys malgaches",
  "MWK": "kwachas malawites",
  "MVR": "rufiyaa maldiviennes",
  "MUR": "roupies mauriciennes",
  "MDL": "lei moldaves",
  "MNT": "tugriks mongols",
  "MAD": "dirhams marocains",
  "MZN": "meticals mozambicains",
  "MMK": "kyats myanmarais",
  "NAD": "dollars namibiens",
  "NPR": "roupies népalaises",
  "NIO": "córdobas nicaraguayens",
  "NGN": "nairas nigérians",
  "OMR": "rials omanais",
  "PKR": "roupies pakistanaises",
  "PGK": "kinas papou-néo-guinéens",
  "PYG": "guaranis paraguayens",
  "PEN": "nouveaux soles péruviens",
  "QAR": "riyals qataris",
  "RWF": "francs rwandais",
  "RSD": "dinars serbes",
  "SCR": "roupies des Seychelles",
  "SOS": "shillings somaliens",
  "LKR": "roupies sri-lankaises",
  "SRD": "dollars surinamais",
  "SYP": "livres syriennes",
  "TZS": "shillings tanzaniens",
  "TOP": "pa'angas tongiens",
  "TTD": "dollars de Trinité-et-Tobago",
  "TND": "dinars tunisiens",
  "UGX": "shillings ougandais",
  "UAH": "hryvnias ukrainiennes",
  "UYU": "pesos uruguayens",
  "VES": "bolívars vénézuéliens",
  "VND": "dongs vietnamiens",
  "YER": "rials yéménites",
  "ZMW": "kwachas zambiens",
  "ZWL": "dollars zimbabwéens",
};
