// ignore_for_file: non_constant_identifier_names

Map<String, String> names_it = {
  "USD": "Dollaro statunitense",
  "EUR": "Euro",
  "JPY": "Yen giapponese",
  "GBP": "Sterlina britannica",
  "AUD": "Dollaro australiano",
  "CAD": "Dollaro canadese",
  "CHF": "Franco svizzero",
  "CNY": "Yuan cinese renminbi",
  "HKD": "Dollaro di Hong Kong",
  "NZD": "Dollaro neozelandese",
  "SEK": "Corona svedese",
  "KRW": "Won sudcoreano",
  "SGD": "Dollaro di Singapore",
  "NOK": "Corona norvegese",
  "MXN": "Peso messicano",
  "INR": "Rupia indiana",
  "RUB": "Rublo russo",
  "ZAR": "Rand sudafricano",
  "TRY": "Lira turca",
  "BRL": "Real brasiliano",
  "TWD": "Nuovo dollaro taiwanese",
  "DKK": "Corona danese",
  "PLN": "Zloty polacco",
  "THB": "Baht thailandese",
  "IDR": "Rupia indonesiana",
  "HUF": "Fiorino ungherese",
  "CZK": "Corona ceca",
  "ILS": "Shekel israeliano",
  "CLP": "Peso cileno",
  "PHP": "Peso filippino",
  "AED": "Dirham degli Emirati Arabi Uniti",
  "COP": "Peso colombiano",
  "SAR": "Riyal saudita",
  "MYR": "Ringgit malese",
  "RON": "Leu rumeno",
  "AFN": "Afghani",
  "ALL": "Lek albanese",
  "DZD": "Dinaro algerino",
  "AOA": "Kwanza angolano",
  "ARS": "Peso argentino",
  "AMD": "Dram armeno",
  "AZN": "Manat azero",
  "BHD": "Dinaro del Bahrein",
  "BDT": "Taka bengalese",
  "BBD": "Dollaro di Barbados",
  "BYN": "Rublo bielorusso",
  "BZD": "Dollaro del Belize",
  "BMD": "Dollaro delle Bermuda",
  "BTN": "Ngultrum bhutanese",
  "BOB": "Boliviano",
  "BAM": "Marco convertibile della Bosnia-Erzegovina",
  "BWP": "Pula del Botswana",
  "BND": "Dollaro del Brunei",
  "BGN": "Lev bulgaro",
  "BIF": "Franco del Burundi",
  "KHR": "Riel cambogiano",
  "KYD": "Dollaro delle Isole Cayman",
  "XAF": "Franco CFA dell'Africa Centrale",
  "XOF": "Franco CFA dell'UEMOA",
  "CDF": "Franco congolese",
  "CRC": "Colón costaricano",
  "CUP": "Peso cubano",
  "DOP": "Peso dominicano",
  "EGP": "Sterlina egiziana",
  "ETB": "Birr etiope",
  "GMD": "Dalasi gambiano",
  "GEL": "Lari georgiano",
  "GHS": "Cedi ghanese",
  "GTQ": "Quetzal guatemalteco",
  "GYD": "Dollaro della Guyana",
  "HTG": "Gourde haitiana",
  "ISK": "Corona islandese",
  "IQD": "Dinaro iracheno",
  "JMD": "Dollaro giamaicano",
  "JOD": "Dinaro giordano",
  "KZT": "Tenge kazako",
  "KES": "Scellino keniota",
  "KWD": "Dinaro kuwaitiano",
  "KGS": "Som kirghiso",
  "LAK": "Kip laotiano",
  "LBP": "Sterlina libanese",
  "LRD": "Dollaro liberiano",
  "MKD": "Denaro macedone",
  "MGA": "Ariary malgascio",
  "MWK": "Kwacha malawiano",
  "MVR": "Rufiyaa delle Maldive",
  "MUR": "Rupia mauriziana",
  "MDL": "Leu moldavo",
  "MNT": "Tugrik mongolo",
  "MAD": "Dirham marocchino",
  "MZN": "Metical mozambicano",
  "MMK": "Kyat birmano",
  "NAD": "Dollaro namibiano",
  "NPR": "Rupia nepalese",
  "NIO": "Cordoba nicaraguense",
  "NGN": "Naira nigeriana",
  "OMR": "Rial omanita",
  "PKR": "Rupia pakistana",
  "PGK": "Kina papuana",
  "PYG": "Guaraní paraguaiano",
  "PEN": "Sol peruviano",
  "QAR": "Riyal del Qatar",
  "RWF": "Franco ruandese",
  "RSD": "Dinaro serbo",
  "SCR": "Rupia delle Seychelles",
  "SOS": "Scellino somalo",
  "LKR": "Rupia di Sri Lanka",
  "SRD": "Dollaro del Suriname",
  "SYP": "Lira siriana",
  "TZS": "Scellino tanzaniano",
  "TOP": "Paʻanga tongano",
  "TTD": "Dollaro di Trinidad e Tobago",
  "TND": "Dinaro tunisino",
  "UGX": "Scellino ugandese",
  "UAH": "Grivnia ucraina",
  "UYU": "Peso uruguaiano",
  "VES": "Bolívar venezuelano",
  "VND": "Dong vietnamita",
  "YER": "Rial yemenita",
  "ZMW": "Kwacha zambiano",
  "ZWL": "Dollaro zimbabwiano",
};

Map<String, String> pluralNames_it = {
  "USD": "Dollari statunitensi",
  "EUR": "Euro",
  "JPY": "Yen giapponesi",
  "GBP": "Sterline britanniche",
  "AUD": "Dollari australiani",
  "CAD": "Dollari canadesi",
  "CHF": "Franchi svizzeri",
  "CNY": "Yuan cinesi",
  "HKD": "Dollari di Hong Kong",
  "NZD": "Dollari neozelandesi",
  "SEK": "Corone svedesi",
  "KRW": "Won sudcoreani",
  "SGD": "Dollari di Singapore",
  "NOK": "Corone norvegesi",
  "MXN": "Pesos messicani",
  "INR": "Rupie indiane",
  "RUB": "Rubli russi",
  "ZAR": "Rand sudafricani",
  "TRY": "Lire turche",
  "BRL": "Reais brasiliani",
  "TWD": "Nuovi dollari taiwanesi",
  "DKK": "Corone danesi",
  "PLN": "Zloty polacchi",
  "THB": "Baht thailandesi",
  "IDR": "Rupie indonesiane",
  "HUF": "Fiorini ungheresi",
  "CZK": "Corone ceche",
  "ILS": "Nuovi sheqel israeliani",
  "CLP": "Pesos cileni",
  "PHP": "Pesos filippini",
  "AED": "Dirham degli Emirati Arabi Uniti",
  "COP": "Pesos colombiani",
  "SAR": "Riyal sauditi",
  "MYR": "Ringgit malesi",
  "RON": "Lei rumeni",
  "AFN": "Afghani afgani",
  "ALL": "Lek albanesi",
  "DZD": "Dinar algerini",
  "AOA": "Kwanza angolani",
  "ARS": "Pesos argentini",
  "AMD": "Dram armeni",
  "AZN": "Manat azeri",
  "BHD": "Dinar del Bahrain",
  "BDT": "Taka bangladeshi",
  "BBD": "Dollari di Barbados",
  "BYN": "Rubli bielorussi",
  "BZD": "Dollari del Belize",
  "BMD": "Dollari delle Bermuda",
  "BTN": "Ngultrum bhutanesi",
  "BOB": "Boliviani boliviani",
  "BAM": "Marchi convertibili della Bosnia ed Erzegovina",
  "BWP": "Pula del Botswana",
  "BND": "Dollari del Brunei",
  "BGN": "Leva bulgari",
  "BIF": "Franchi burundesi",
  "KHR": "Riel cambogiani",
  "KYD": "Dollari delle Isole Cayman",
  "XAF": "Franchi CFA dell'Africa centrale",
  "XOF": "Franchi CFA dell'UEMOA",
  "CDF": "Franchi congolesi",
  "CRC": "Colón costaricani",
  "CUP": "Pesos cubani",
  "DOP": "Pesos dominicani",
  "EGP": "Sterline egiziane",
  "ETB": "Birr etiopi",
  "GMD": "Dalasi gambiani",
  "GEL": "Lari georgiani",
  "GHS": "Cedi ghanesi",
  "GTQ": "Quetzales guatemaltechi",
  "GYD": "Dollari della Guyana",
  "HTG": "Gourde haitiane",
  "ISK": "Corone islandesi",
  "IQD": "Dinar iracheni",
  "JMD": "Dollari giamaicani",
  "JOD": "Dinar giordani",
  "KZT": "Tenge kazaki",
  "KES": "Scellini kenioti",
  "KWD": "Dinar kuwaitiani",
  "KGS": "Som kirghisi",
  "LAK": "Kip laotiani",
  "LBP": "Sterline libanesi",
  "LRD": "Dollari liberiani",
  "MKD": "Denari macedoni",
  "MGA": "Ariary malgasci",
  "MWK": "Kwacha malawiani",
  "MVR": "Rufiyaa maldiviane",
  "MUR": "Rupie mauriziane",
  "MDL": "Lei moldavi",
  "MNT": "Tugrik mongoli",
  "MAD": "Dirham marocchini",
  "MZN": "Metical mozambicani",
  "MMK": "Kyat birmani",
  "NAD": "Dollari namibiani",
  "NPR": "Rupie nepalesi",
  "NIO": "Córdoba nicaraguensi",
  "NGN": "Naira nigeriani",
  "OMR": "Rial omaniti",
  "PKR": "Rupie pakistane",
  "PGK": "Kina papuani",
  "PYG": "Guaraní paraguaiani",
  "PEN": "Nuevos soles peruviani",
  "QAR": "Riyal qatarioti",
  "RWF": "Franchi ruandesi",
  "RSD": "Dinar serbi",
  "SCR": "Rupie delle Seychelles",
  "SOS": "Scellini somali",
  "LKR": "Rupie srilankesi",
  "SRD": "Dollari surinamesi",
  "SYP": "Lire siriane",
  "TZS": "Scellini tanzaniani",
  "TOP": "Paʻanga tongani",
  "TTD": "Dollari di Trinidad e Tobago",
  "TND": "Dinar tunisini",
  "UGX": "Scellini ugandesi",
  "UAH": "Hryvnia ucraine",
  "UYU": "Pesos uruguaiani",
  "VES": "Bolívar venezuelani",
  "VND": "Dong vietnamiti",
  "YER": "Rial yemeniti",
  "ZMW": "Kwacha zambiani",
  "ZWL": "Dollari dello Zimbabwe",
};
