// ignore_for_file: non_constant_identifier_names

Map<String, String> names_nl = {
  "USD": "Amerikaanse dollar",
  "EUR": "Euro",
  "JPY": "Japanse yen",
  "GBP": "Britse pond",
  "AUD": "Australische dollar",
  "CAD": "Canadese dollar",
  "CHF": "Zwitserse frank",
  "CNY": "Chinese yuan renminbi",
  "HKD": "Hongkong dollar",
  "NZD": "Nieuw-Zeelandse dollar",
  "SEK": "Zweedse kroon",
  "KRW": "Zuid-Koreaanse won",
  "SGD": "Singaporese dollar",
  "NOK": "Noorse kroon",
  "MXN": "Mexicaanse peso",
  "INR": "Indiase roepie",
  "RUB": "Russische roebel",
  "ZAR": "Zuid-Afrikaanse rand",
  "TRY": "Turkse lira",
  "BRL": "Braziliaanse real",
  "TWD": "Taiwanese dollar",
  "DKK": "Deense kroon",
  "PLN": "Poolse zloty",
  "THB": "Thaise baht",
  "IDR": "Indonesische roepia",
  "HUF": "Hongaarse forint",
  "CZK": "Tsjechische kroon",
  "ILS": "Israëlische sjekel",
  "CLP": "Chileense peso",
  "PHP": "Filipijnse peso",
  "AED": "VAE-dirham",
  "COP": "Colombiaanse peso",
  "SAR": "Saoedi-Arabische riyal",
  "MYR": "Maleisische ringgit",
  "RON": "Roemeense leu",
  "AFN": "Afghaanse afghani",
  "ALL": "Albanese lek",
  "DZD": "Algerijnse dinar",
  "AOA": "Angolese kwanza",
  "ARS": "Argentijnse peso",
  "AMD": "Armeense dram",
  "AZN": "Azerbeidzjaanse manat",
  "BHD": "Bahreinse dinar",
  "BDT": "Bengaalse taka",
  "BBD": "Barbadaanse dollar",
  "BYN": "Wit-Russische roebel",
  "BZD": "Belizaanse dollar",
  "BMD": "Bermuda dollar",
  "BTN": "Bhutaanse ngultrum",
  "BOB": "Boliviaanse boliviano",
  "BAM": "Bosnische convertibele mark",
  "BWP": "Botswaanse pula",
  "BND": "Bruneise dollar",
  "BGN": "Bulgaarse lev",
  "BIF": "Burundese frank",
  "KHR": "Cambodjaanse riel",
  "KYD": "Kaaimaneilandse dollar",
  "XAF": "Centraal-Afrikaanse CFA-frank",
  "XOF": "West-Afrikaanse CFA-frank",
  "CDF": "Congolese frank",
  "CRC": "Costa Ricaanse colon",
  "CUP": "Cubaanse peso",
  "DOP": "Dominicaanse peso",
  "EGP": "Egyptisch pond",
  "ETB": "Ethiopische birr",
  "GMD": "Gambiaanse dalasi",
  "GEL": "Georgische lari",
  "GHS": "Ghanese cedi",
  "GTQ": "Guatemalteekse quetzal",
  "GYD": "Guyaanse dollar",
  "HTG": "Haïtiaanse gourde",
  "ISK": "IJslandse kroon",
  "IQD": "Iraakse dinar",
  "JMD": "Jamaicaanse dollar",
  "JOD": "Jordaanse dinar",
  "KZT": "Kazachse tenge",
  "KES": "Keniaanse shilling",
  "KWD": "Koeweitse dinar",
  "KGS": "Kirgizische som",
  "LAK": "Laotiaanse kip",
  "LBP": "Libanese pond",
  "LRD": "Liberiaanse dollar",
  "MKD": "Macedonische denar",
  "MGA": "Malagassische ariary",
  "MWK": "Malawische kwacha",
  "MVR": "Maldivische rufiyaa",
  "MUR": "Mauritiaanse roepie",
  "MDL": "Moldavische leu",
  "MNT": "Mongoolse tugrik",
  "MAD": "Marokkaanse dirham",
  "MZN": "Mozambikaanse metical",
  "MMK": "Myanmarese kyat",
  "NAD": "Namibische dollar",
  "NPR": "Nepalese roepie",
  "NIO": "Nicaraguaanse cordoba",
  "NGN": "Nigeriaanse naira",
  "OMR": "Omaanse rial",
  "PKR": "Pakistaanse roepie",
  "PGK": "Papoea-Nieuw-Guinese kina",
  "PYG": "Paraguayaanse guarani",
  "PEN": "Peruaanse sol",
  "QAR": "Qatarese riyal",
  "RWF": "Rwandese frank",
  "RSD": "Servische dinar",
  "SCR": "Seychelse roepie",
  "SOS": "Somalische shilling",
  "LKR": "Sri Lankaanse roepie",
  "SRD": "Surinaamse dollar",
  "SYP": "Syrische lira",
  "TZS": "Tanzaniaanse shilling",
  "TOP": "Tongaanse pa'anga",
  "TTD": "Trinidad en Tobago dollar",
  "TND": "Tunesische dinar",
  "UGX": "Oegandese shilling",
  "UAH": "Oekraïense hryvnia",
  "UYU": "Uruguayaanse peso",
  "VES": "Venezolaanse bolívar",
  "VND": "Vietnamese dong",
  "YER": "Jemenitische rial",
  "ZMW": "Zambiaanse kwacha",
  "ZWL": "Zimbabwaanse dollar",
};

Map<String, String> pluralNames_nl = {
  "USD": "Amerikaanse dollars",
  "EUR": "Euro's",
  "JPY": "Japanse yen",
  "GBP": "Britse ponden",
  "AUD": "Australische dollars",
  "CAD": "Canadese dollars",
  "CHF": "Zwitserse franken",
  "CNY": "Chinese yuan",
  "HKD": "Hongkong-dollars",
  "NZD": "Nieuw-Zeelandse dollars",
  "SEK": "Zweedse kronen",
  "KRW": "Zuid-Koreaanse won",
  "SGD": "Singaporese dollars",
  "NOK": "Noorse kronen",
  "MXN": "Mexicaanse peso's",
  "INR": "Indiase roepies",
  "RUB": "Russische roebels",
  "ZAR": "Zuid-Afrikaanse rand",
  "TRY": "Turkse lira",
  "BRL": "Braziliaanse reais",
  "TWD": "Nieuwe Taiwanese dollars",
  "DKK": "Deense kronen",
  "PLN": "Poolse zloty's",
  "THB": "Thaise baht",
  "IDR": "Indonesische roepia's",
  "HUF": "Hongaarse forinten",
  "CZK": "Tsjechische kronen",
  "ILS": "Israëlische nieuwe sjekels",
  "CLP": "Chileense peso's",
  "PHP": "Filipijnse peso's",
  "AED": "VAE-dirhams",
  "COP": "Colombiaanse peso's",
  "SAR": "Saoedische riyals",
  "MYR": "Maleisische ringgits",
  "RON": "Roemeense lei",
  "AFN": "Afghaanse afghanis",
  "ALL": "Albanese lekë",
  "DZD": "Algerijnse dinars",
  "AOA": "Angolese kwanzas",
  "ARS": "Argentijnse peso's",
  "AMD": "Armeense dram",
  "AZN": "Azerbeidzjaanse manats",
  "BHD": "Bahreinse dinars",
  "BDT": "Bengalese taka's",
  "BBD": "Barbados-dollars",
  "BYN": "Wit-Russische roebels",
  "BZD": "Belize-dollars",
  "BMD": "Bermuda-dollars",
  "BTN": "Bhutaanse ngultrums",
  "BOB": "Boliviaanse boliviano's",
  "BAM": "Bosnische converteerbare marken",
  "BWP": "Botswaanse pula's",
  "BND": "Bruneise dollars",
  "BGN": "Bulgaarse leva",
  "BIF": "Burundese frank",
  "KHR": "Cambodjaanse riel",
  "KYD": "Kaaimaneilandse dollars",
  "XAF": "Centraal-Afrikaanse CFA-franken",
  "XOF": "West-Afrikaanse CFA-franken",
  "CDF": "Congolese franken",
  "CRC": "Costa Ricaanse colóns",
  "CUP": "Cubaanse peso's",
  "DOP": "Dominicaanse peso's",
  "EGP": "Egyptische ponden",
  "ETB": "Ethiopische birrs",
  "GMD": "Gambiaanse dalasi's",
  "GEL": "Georgische lari's",
  "GHS": "Ghanese cedi's",
  "GTQ": "Guatemalteekse quetzales",
  "GYD": "Guyaanse dollars",
  "HTG": "Haïtiaanse gourdes",
  "ISK": "IJslandse kronen",
  "IQD": "Iraakse dinars",
  "JMD": "Jamaicaanse dollars",
  "JOD": "Jordaanse dinars",
  "KZT": "Kazachse tenges",
  "KES": "Keniaanse shillings",
  "KWD": "Koeweitse dinars",
  "KGS": "Kirgizische som",
  "LAK": "Laotiaanse kip",
  "LBP": "Libanese ponden",
  "LRD": "Liberiaanse dollars",
  "MKD": "Macedonische denars",
  "MGA": "Malagassische ariary's",
  "MWK": "Malawische kwacha's",
  "MVR": "Maldivische rufiyaa's",
  "MUR": "Mauritiaanse roepies",
  "MDL": "Moldavische lei",
  "MNT": "Mongoolse tugriks",
  "MAD": "Marokkaanse dirhams",
  "MZN": "Mozambikaanse meticals",
  "MMK": "Myanmarese kyat",
  "NAD": "Namibische dollars",
  "NPR": "Nepalese roepies",
  "NIO": "Nicaraguaanse córdobas",
  "NGN": "Nigeriaanse naira's",
  "OMR": "Omaanse rials",
  "PKR": "Pakistaanse roepies",
  "PGK": "Papoea-Nieuw-Guinese kina",
  "PYG": "Paraguayaanse guaraní's",
  "PEN": "Peruaanse nuevo soles",
  "QAR": "Qatarese rials",
  "RWF": "Rwandese franken",
  "RSD": "Servische dinars",
  "SCR": "Seychelse roepies",
  "SOS": "Somalische shillings",
  "LKR": "Sri Lankaanse roepies",
  "SRD": "Surinaamse dollars",
  "SYP": "Syrische lira",
  "TZS": "Tanzaniaanse shillings",
  "TOP": "Tongaanse pa'angas",
  "TTD": "Trinidad en Tobago-dollars",
  "TND": "Tunesische dinars",
  "UGX": "Oegandese shillings",
  "UAH": "Oekraïense hryvnia's",
  "UYU": "Uruguayaanse peso's",
  "VEF": "Venezolaanse bolívars",
  "VND": "Vietnamese dong",
  "YER": "Jemenitische rials",
  "ZMW": "Zambiaanse kwacha's",
  "ZWL": "Zimbabwaanse dollars",
};
