// ignore_for_file: non_constant_identifier_names

Map<String, String> names_sv = {
  "USD": "Amerikansk dollar",
  "EUR": "Euro",
  "JPY": "Japansk yen",
  "GBP": "Brittiskt pund",
  "AUD": "Australisk dollar",
  "CAD": "Kanadensisk dollar",
  "CHF": "Schweizisk franc",
  "CNY": "Kinesisk yuan",
  "HKD": "Hongkong-dollar",
  "NZD": "Nyzeeländsk dollar",
  "SEK": "Svensk krona",
  "KRW": "Sydkoreansk won",
  "SGD": "Singaporiansk dollar",
  "NOK": "Norsk krona",
  "MXN": "Mexikansk peso",
  "INR": "Indisk rupie",
  "RUB": "Rysk rubel",
  "ZAR": "Sydafrikansk rand",
  "TRY": "Turkisk lira",
  "BRL": "Brasiliansk real",
  "TWD": "Taiwanesisk dollar",
  "DKK": "Dansk krona",
  "PLN": "Polsk zloty",
  "THB": "Thailändsk baht",
  "IDR": "Indonesisk rupiah",
  "HUF": "Ungersk forint",
  "CZK": "Tjeckisk koruna",
  "ILS": "Israelisk shekel",
  "CLP": "Chilensk peso",
  "PHP": "Filippinsk peso",
  "AED": "Emiratisk dirham",
  "COP": "Colombiansk peso",
  "SAR": "Saudiarabisk riyal",
  "MYR": "Malaysisk ringgit",
  "RON": "Rumänsk leu",
  "AFN": "Afghansk afghani",
  "ALL": "Albansk lek",
  "DZD": "Algerisk dinar",
  "AOA": "Angolansk kwanza",
  "ARS": "Argentinsk peso",
  "AMD": "Armenisk dram",
  "AZN": "Azerbajdzjansk manat",
  "BHD": "Bahrainsk dinar",
  "BDT": "Bangladeshisk taka",
  "BBD": "Barbadisk dollar",
  "BYN": "Vitrysk rubel",
  "BZD": "Belizisk dollar",
  "BMD": "Bermudisk dollar",
  "BTN": "Bhutanesisk ngultrum",
  "BOB": "Boliviansk boliviano",
  "BAM": "Bosnisk-konvertibel mark",
  "BWP": "Botswansk pula",
  "BND": "Bruneisk dollar",
  "BGN": "Bulgarisk lev",
  "BIF": "Burundisk franc",
  "KHR": "Kambodjansk riel",
  "KYD": "Caymansk dollar",
  "XAF": "Centralafrikansk CFA-franc",
  "XOF": "Västafrikansk CFA-franc",
  "CDF": "Kongolesisk franc",
  "CRC": "Costaricansk colón",
  "CUP": "Kubansk peso",
  "DOP": "Dominikansk peso",
  "EGP": "Egyptiskt pund",
  "ETB": "Etiopisk birr",
  "GMD": "Gambisk dalasi",
  "GEL": "Georgisk lari",
  "GHS": "Ghanansk cedi",
  "GTQ": "Guatemalansk quetzal",
  "GYD": "Guyansk dollar",
  "HTG": "Haitisk gourde",
  "ISK": "Isländsk krona",
  "IQD": "Irakisk dinar",
  "JMD": "Jamaicansk dollar",
  "JOD": "Jordansk dinar",
  "KZT": "Kazakisk tenge",
  "KES": "Kenyansk shilling",
  "KWD": "Kuwaitisk dinar",
  "KGS": "Kirgizisk som",
  "LAK": "Laotisk kip",
  "LBP": "Libanesiskt pund",
  "LRD": "Liberisk dollar",
  "MKD": "Makedonisk denar",
  "MGA": "Madagaskisk ariary",
  "MWK": "Malawisk kwacha",
  "MVR": "Maldivisk rufiyaa",
  "MUR": "Mauritisk rupie",
  "MDL": "Moldavisk leu",
  "MNT": "Mongolisk tugrik",
  "MAD": "Marockansk dirham",
  "MZN": "Mozambikisk metical",
  "MMK": "Myanmarsk kyat",
  "NAD": "Namibisk dollar",
  "NPR": "Nepalesisk rupie",
  "NIO": "Nicaraguansk cordoba",
  "NGN": "Nigeriansk naira",
  "OMR": "Omansk rial",
  "PKR": "Pakistansk rupie",
  "PGK": "Papuansk kina",
  "PYG": "Paraguayansk guarani",
  "PEN": "Peruansk sol",
  "QAR": "Qatarisk rial",
  "RWF": "Rwandisk franc",
  "RSD": "Serbisk dinar",
  "SCR": "Seychellisk rupie",
  "SOS": "Somalisk shilling",
  "LKR": "Sri lankesisk rupie",
  "SRD": "Surinamesisk dollar",
  "SYP": "Syrisk lira",
  "TZS": "Tanzanisk shilling",
  "TOP": "Tongansk paʻanga",
  "TTD": "Trinidadisk dollar",
  "TND": "Tunisisk dinar",
  "UGX": "Ugandisk shilling",
  "UAH": "Ukrainsk hryvnia",
  "UYU": "Uruguayansk peso",
  "VES": "Venezuelansk bolívar",
  "VND": "Vietnamesisk dong",
  "YER": "Jemenitisk rial",
  "ZMW": "Zambisk kwacha",
  "ZWL": "Zimbabwisk dollar",
};

Map<String, String> pluralNames_sv = {
  "USD": "Amerikanska dollar",
  "EUR": "Euros",
  "JPY": "Japanska yen",
  "GBP": "Brittiska pund",
  "AUD": "Australiska dollar",
  "CAD": "Kanadensiska dollar",
  "CHF": "Schweiziska franc",
  "CNY": "Kinesiska yuan",
  "HKD": "Hongkong-dollar",
  "NZD": "Nyzeeländska dollar",
  "SEK": "Svenska kronor",
  "KRW": "Sydkoreanska won",
  "SGD": "Singaporianska dollar",
  "NOK": "Norska kronor",
  "MXN": "Mexikanska pesos",
  "INR": "Indiska rupier",
  "RUB": "Ryska rubel",
  "ZAR": "Sydafrikanska rand",
  "TRY": "Turkiska lira",
  "BRL": "Brasilianska reais",
  "TWD": "Taiwanesiska nya dollar",
  "DKK": "Danska kronor",
  "PLN": "Polska zloty",
  "THB": "Thailändska baht",
  "IDR": "Indonesiska rupier",
  "HUF": "Ungerska forinter",
  "CZK": "Tjeckiska korunas",
  "ILS": "Israeliska nya sheqel",
  "CLP": "Chilenska pesos",
  "PHP": "Filippinska pesos",
  "AED": "Förenade Arabemiratens dirham",
  "COP": "Colombianska pesos",
  "SAR": "Saudiska rial",
  "MYR": "Malaysiska ringgit",
  "RON": "Rumänska lei",
  "AFN": "Afghanska afghani",
  "ALL": "Albanska lekë",
  "DZD": "Algeriska dinarer",
  "AOA": "Angolanska kwanza",
  "ARS": "Argentinska pesos",
  "AMD": "Armeniska dram",
  "AZN": "Azerbajdzjanska manat",
  "BHD": "Bahrainska dinarer",
  "BDT": "Bangladeshiska taka",
  "BBD": "Barbados-dollar",
  "BYN": "Vitryska rubel",
  "BZD": "Belize-dollar",
  "BMD": "Bermuda-dollar",
  "BTN": "Bhutanesiska ngultrum",
  "BOB": "Bolivianska bolivianos",
  "BAM": "Bosnien-Hercegovinas konvertibla mark",
  "BWP": "Botswanska pula",
  "BND": "Brunei-dollar",
  "BGN": "Bulgariska leva",
  "BIF": "Burundiska franc",
  "KHR": "Kambodjanska riel",
  "KYD": "Cayman-dollar",
  "XAF": "CFA-franc (Centralafrika)",
  "XOF": "CFA-franc (Västafrika)",
  "CDF": "Kongolesiska franc",
  "CRC": "Costa Ricas colóns",
  "CUP": "Kubanska pesos",
  "DOP": "Dominikanska pesos",
  "EGP": "Egyptiska pund",
  "ETB": "Etiopiska birr",
  "GMD": "Gambiska dalasis",
  "GEL": "Georgiska lari",
  "GHS": "Ghananska cedi",
  "GTQ": "Guatemalanska quetzales",
  "GYD": "Guyana-dollar",
  "HTG": "Haitiska gourdes",
  "ISK": "Isländska krónur",
  "IQD": "Irakiska dinarer",
  "JMD": "Jamaica-dollar",
  "JOD": "Jordanska dinarer",
  "KZT": "Kazakiska tenges",
  "KES": "Kenyanska shilling",
  "KWD": "Kuwaitiska dinarer",
  "KGS": "Kirgiziska som",
  "LAK": "Laotiska kip",
  "LBP": "Libanesiska pund",
  "LRD": "Liberiska dollar",
  "MKD": "Makedonska denari",
  "MGA": "Madagaskiska ariary",
  "MWK": "Malawiska kwacha",
  "MVR": "Maldiviska rufiyaa",
  "MUR": "Mauritiska rupier",
  "MDL": "Moldaviska lei",
  "MNT": "Mongoliska tugrik",
  "MAD": "Marockanska dirham",
  "MZN": "Moçambikiska metical",
  "MMK": "Burmesiska kyat",
  "NAD": "Namibiska dollar",
  "NPR": "Nepalesiska rupier",
  "NIO": "Nicaraguanska córdobas",
  "NGN": "Nigerianska naira",
  "OMR": "Omanska rial",
  "PKR": "Pakistanska rupier",
  "PGK": "Papua Nya Guineanska kina",
  "PYG": "Paraguayanska guaranis",
  "PEN": "Peruanska nuevos soles",
  "QAR": "Qatariska rial",
  "RWF": "Rwandiska franc",
  "RSD": "Serbiska dinarer",
  "SCR": "Seychelliska rupier",
  "SOS": "Somaliska shilling",
  "LKR": "Sri Lankesiska rupier",
  "SRD": "Surinamesiska dollar",
  "SYP": "Syriska lira",
  "TZS": "Tanzaniska shilling",
  "TOP": "Tonganska pa'angas",
  "TTD": "Trinidad och Tobago-dollar",
  "TND": "Tunisiska dinarer",
  "UGX": "Ugandiska shilling",
  "UAH": "Ukrainska hryvnias",
  "UYU": "Uruguayanska pesos",
  "VES": "Venezuelanska bolívar",
  "VND": "Vietnamesiska dong",
  "YER": "Jemenitiska rial",
  "ZMW": "Zambiska kwacha",
  "ZWL": "Zimbabwiska dollar",
};
